//user
###
Get http://localhost:3000/api/users
###
Get http://localhost:3000/api/users/1
###
Get http://localhost:3000/api/users/999

###
//สร้าง user ใหม่ถูกต้อง
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username" : "user01",
    "password" : "user1234",
    "firstname" : "user01firstname",
    "lastname" : "user01lastname"
}

###
//สร้าง user ไม่ใหม่ถูกต้อง
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username" : "user01",
    "firstname" : "user01firstname",
    "lastname" : "user01lastname"
}

//role
###
Get http://localhost:3000/api/roles/1
###
Get http://localhost:3000/api/roles/99

###
//สร้าง user ไม่ใหม่ถูกต้อง
POST http://localhost:3000/api/roles
Content-Type: application/json
{
    "name" : "abc"
}

//lap crud
//1
###
Get http://localhost:3000/api/roles

//2
###
Get http://localhost:3000/api/roles/1

//3
###
Get http://localhost:3000/api/roles/2

###
//4
POST http://localhost:3000/api/roles
Content-Type: application/json

{
    "name" : "admin"
}
###
//5
POST http://localhost:3000/api/roles
Content-Type: application/json

{
    "name" : "admi"
}

#6
###
PUT http://localhost:3000/api/roles/4
Content-Type: application/json

{
    "name" : "Director"
}

#7
###
PUT http://localhost:3000/api/roles/4
Content-Type: application/json

{
    "name" : "abcd"
}

#8
###
PATCH  http://localhost:3000/api/roles/2
Content-Type: application/json

{
    "name" : "Trainee"
}

#9
###
PATCH  http://localhost:3000/api/roles/99
Content-Type: application/json

{
    "name" : "Trainee"
}
###
DELETE http://localhost:3000/api/roles/5

###
DELETE http://localhost:3000/api/roles/99